services:
#    ecommerce.example:
#        class: Ecommerce\EcommerceBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
#  service.addProduct:
#    class: EcommerceBundle\Services\ProductsService
#    arguments: ["@doctrine.orm.entity_manager"]
